from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "notebooks/008-hunyuan3d-2.1.ipynb"
SETUP = ROOT / "notebooks/hunyuan3d21_setup.py"
WORKER = ROOT / "notebooks/hunyuan3d21_worker.py"


def code_cell(cell_id: str, source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": cell_id,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


def markdown_cell(cell_id: str, source: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": cell_id,
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def materialize_cell() -> str:
    setup = SETUP.read_text(encoding="utf-8")
    worker = WORKER.read_text(encoding="utf-8")
    return (
        "from pathlib import Path\n\n"
        f"SETUP_SOURCE = {setup!r}\n"
        f"WORKER_SOURCE = {worker!r}\n\n"
        "Path('/kaggle/working/hunyuan3d21_setup.py').write_text(SETUP_SOURCE, encoding='utf-8')\n"
        "Path('/kaggle/working/hunyuan3d21_worker.py').write_text(WORKER_SOURCE, encoding='utf-8')\n"
        "print('✅ Hunyuan3D 2.1 helper modules materialized')\n"
    )


def main() -> None:
    notebook = {
        "cells": [
            markdown_cell(
                "hy21-title",
                "# 008 · Hunyuan3D 2.1 · Kaggle 2×T4\n\n"
                "Canonical code lives in `hunyuan3d21_setup.py` and `hunyuan3d21_worker.py`; "
                "this notebook is generated by `scripts/sync_hunyuan3d21_notebook.py`.\n",
            ),
            code_cell("hy21-materialize", materialize_cell()),
            code_cell(
                "hy21-setup",
                "import subprocess, sys\n"
                "subprocess.run([sys.executable, '/kaggle/working/hunyuan3d21_setup.py'], check=True)\n",
            ),
            code_cell(
                "hy21-run",
                "import subprocess\n"
                "subprocess.run([\n"
                "    '/kaggle/working/hy21-venv/bin/python',\n"
                "    '/kaggle/working/hunyuan3d21_worker.py',\n"
                "], check=True, timeout=2700)\n",
            ),
            markdown_cell(
                "hy21-validation",
                "## 验收\n\n"
                "成功必须出现 `[HY21_SHAPE]`、`[HY21_PAINT]`、`[HY21_EXPORT]`、"
                "`[HY21_RESULT]` 和最终成功标记。\n",
            ),
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    NOTEBOOK.write_text(
        json.dumps(notebook, ensure_ascii=False, indent=1) + "\n", encoding="utf-8"
    )
    print(f"Synced {SETUP.name} + {WORKER.name} -> {NOTEBOOK.name}")


if __name__ == "__main__":
    main()
